<?xml version="1.0" encoding="utf-8"?><Database Name="Bank" Class="BankDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-EKR82M7;Initial Catalog=Bank;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="BankConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="customer_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="credit_score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenure" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="products_number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="credit_card" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="active_member" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="estimated_salary" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="churn" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>